Use process exec values to scrape metrics

diff --git a/.github/workflows/soak-testing.yml b/.github/workflows/soak-testing.yml
--- a/.github/workflows/soak-testing.yml
+++ b/.github/workflows/soak-testing.yml
@@ -18,10 +18,10 @@ on:
   #   - cron: '0 15 * * *'
 env:
   # NOTE: The configuration of `APP_PROCESS_EXECUTABLE_NAME` is repo dependent
-  APP_PROCESS_EXECUTABLE_NAME: EXAMPLE_OF_SOMETHING
+  APP_PROCESS_EXECUTABLE_NAME: ruby
   AWS_DEFAULT_REGION: us-east-1
   DEFAULT_TEST_DURATION_MINUTES: 300
-  HOSTMETRICS_INTERVAL_SECS: 60
+  HOSTMETRICS_INTERVAL_SECS: 600
   CPU_LOAD_THRESHOLD: 50
   TOTAL_MEMORY_THRESHOLD: 1073741824 # 1 GiB
   MAX_BENCHMARKS_TO_KEEP: 100
@@ -42,11 +42,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        app-platform: [ rails ]
+        app-platform: [ ruby-on-rails ]
         instrumentation-type: [ manual ]
     env:
       # NOTE: The configuration of `APP_PATH` is repo dependent
-      APP_PATH: sample-apps
+      APP_PATH: sample-apps/${{ matrix.instrumentation-type}}-instrumentation/${{ matrix.app-platform }}
       LOGS_NAMESPACE: ${{ github.repository }}/soak-tests-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
     steps:
     # MARK: - GitHub Workflow Event Type Specific Values
@@ -75,7 +75,7 @@ jobs:
         if: ${{ matrix.instrumentation-type == 'manual' }}
         run: |
           echo 'APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE<<EOF' >> $GITHUB_ENV
-          echo 'EXAMPLE_OF_SOMETHING' | tee --append $GITHUB_ENV;
+          echo 'puma 5.5.2 (tcp://0.0.0.0:8080) [app]' | tee --append $GITHUB_ENV;
           echo 'EOF' >> $GITHUB_ENV
 
     # MARK: - Uniquely identify this Sample App environment
@@ -135,102 +135,102 @@ jobs:
 
     # MARK: - Report on Performance Test Results
 
-      # - name: Install script dependencies
-      #   run: pip install boto3
-      # - name: Get a snapshot of metrics and commit them to the repository
-      #   run: |
-      #     python3 .github/scripts/performance-tests/produce_metric_widget_images.py \
-      #       --logs-namespace ${{ env.LOGS_NAMESPACE }} \
-      #       --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }} \
-      #       --num-of-cpus ${{ env.NUM_OF_CPUS }} \
-      #       --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}" \
-      #       --target-sha ${{ env.TARGET_SHA }} \
-      #       --github-run-id ${GITHUB_RUN_ID} \
-      #       --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }} \
-      #       --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }} \
-      #       --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }} \
-      #       --app-platform ${{ matrix.app-platform }} \
-      #       --instrumentation-type ${{ matrix.instrumentation-type }} \
-      #       --max-benchmarks-to-keep ${{ env.MAX_BENCHMARKS_TO_KEEP }} \
-      #       --github-repository ${GITHUB_REPOSITORY}
-      #     echo "::warning::Checkout Snapshots at this link: https://github.com/${GITHUB_REPOSITORY}/blob/gh-pages/soak-tests/snapshots/commits/${{ env.TARGET_SHA }}/runs/${GITHUB_RUN_ID}/${{ matrix.app-platform }}";
-      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
-      #     git config user.name "GitHub Actions";
-      #     git fetch;
-      #     git checkout gh-pages;
-      #     git add soak-tests/snapshots/commits;
-      #     git commit -m "Soak Test Snapshots from ${{ env.TARGET_SHA }} - ${GITHUB_RUN_ID}";
-      #     git push;
-      #     git checkout main;
-      # - name: Prepare Performance Test results as JSON output
-      #   run: python3 .github/scripts/performance-tests/get-metric-data/produce_performance_test_results.py
-      #     --logs-namespace ${{ env.LOGS_NAMESPACE }}
-      #     --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
-      #     --num-of-cpus ${{ env.NUM_OF_CPUS }}
-      #     --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
-      #     --target-sha ${{ env.TARGET_SHA }}
-      #     --github-run-id ${GITHUB_RUN_ID}
-      #     --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
-      # - name: Do we already have Performance Test graph results for this commit?
-      #   continue-on-error: true
-      #   id: check-already-have-performance-results
-      #   run: |
-      #     git checkout gh-pages;
-      #     HAS_RESULTS_ALREADY=$(
-      #       sed 's/window.BENCHMARK_DATA = //' soak-tests/per-commit-overall-results/data.js |
-      #       jq "
-      #         .entries |
-      #         .\"Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}\" |
-      #         any(.commit.id == \"${{ env.TARGET_SHA }}\")
-      #       " || echo false
-      #     );
-      #     git checkout main;
-      #     [[ $HAS_RESULTS_ALREADY == true ]]
-      # - name: Graph and Report Performance Test Averages result
-      #   uses: benchmark-action/github-action-benchmark@v1
-      #   continue-on-error: true
-      #   id: check-failure-after-performance-tests
-      #   with:
-      #     name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
-      #     tool: customSmallerIsBetter
-      #     output-file-path: output.json
-      #     github-token: ${{ secrets.GITHUB_TOKEN }}
-      #     max-items-in-chart: ${{ env.MAX_BENCHMARKS_TO_KEEP }}
-      #     alert-threshold: 175%
-      #     # Does not work as expected, see:
-      #     # https://github.com/open-telemetry/opentelemetry-python/pull/1478
-      #     # comment-always: true
-      #     fail-on-alert: true
-      #     auto-push: ${{ github.event_name == 'schedule' &&
-      #       steps.check-already-have-performance-results.outcome == 'failure' &&
-      #       github.ref == 'refs/heads/main' }}
-      #     gh-pages-branch: gh-pages
-      #     benchmark-data-dir-path: soak-tests/per-commit-overall-results
-      # - name: Publish Issue if failed DURING Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: ${{ github.event_name == 'schedule' &&
-      #     steps.check-failure-during-performance-tests.outcome == 'failure' }}
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/auto-issue-templates/failure-during-soak_tests.md
-      #     update_existing: true
-      # - name: Publish Issue if failed AFTER Performance Tests
-      #   uses: JasonEtco/create-an-issue@v2
-      #   if: ${{ github.event_name == 'schedule' &&
-      #     steps.check-failure-after-performance-tests.outcome == 'failure' }}
-      #   env:
-      #     APP_PLATFORM: ${{ matrix.app-platform }}
-      #     INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   with:
-      #     filename: .github/auto-issue-templates/failure-after-soak_tests.md
-      #     update_existing: true
-      # - name: Check for Performance Degradation either DURING or AFTER Performance Tests
-      #   if: ${{ steps.check-failure-during-performance-tests.outcome == 'failure' ||
-      #     steps.check-failure-after-performance-tests.outcome == 'failure' }}
-      #   run: >-
-      #     echo 'Performance Tests failed, see the logs above for details';
-      #     exit 1;
+      - name: Install script dependencies
+        run: pip install boto3
+      - name: Get a snapshot of metrics and commit them to the repository
+        run: |
+          python3 .github/scripts/performance-tests/produce_metric_widget_images.py \
+            --logs-namespace ${{ env.LOGS_NAMESPACE }} \
+            --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }} \
+            --num-of-cpus ${{ env.NUM_OF_CPUS }} \
+            --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}" \
+            --target-sha ${{ env.TARGET_SHA }} \
+            --github-run-id ${GITHUB_RUN_ID} \
+            --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }} \
+            --cpu-load-threshold ${{ env.CPU_LOAD_THRESHOLD }} \
+            --total-memory-threshold ${{ env.TOTAL_MEMORY_THRESHOLD }} \
+            --app-platform ${{ matrix.app-platform }} \
+            --instrumentation-type ${{ matrix.instrumentation-type }} \
+            --max-benchmarks-to-keep ${{ env.MAX_BENCHMARKS_TO_KEEP }} \
+            --github-repository ${GITHUB_REPOSITORY}
+          echo "::warning::Checkout Snapshots at this link: https://github.com/${GITHUB_REPOSITORY}/blob/gh-pages/soak-tests/snapshots/commits/${{ env.TARGET_SHA }}/runs/${GITHUB_RUN_ID}/${{ matrix.app-platform }}";
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com";
+          git config user.name "GitHub Actions";
+          git fetch;
+          git checkout gh-pages;
+          git add soak-tests/snapshots/commits;
+          git commit -m "Soak Test Snapshots from ${{ env.TARGET_SHA }} - ${GITHUB_RUN_ID}";
+          git push;
+          git checkout main;
+      - name: Prepare Performance Test results as JSON output
+        run: python3 .github/scripts/performance-tests/get-metric-data/produce_performance_test_results.py
+          --logs-namespace ${{ env.LOGS_NAMESPACE }}
+          --metrics-period ${{ env.HOSTMETRICS_INTERVAL_SECS }}
+          --num-of-cpus ${{ env.NUM_OF_CPUS }}
+          --app-process-command-line-dimension-value "${{ env.APP_PROCESS_COMMAND_LINE_DIMENSION_VALUE }}"
+          --target-sha ${{ env.TARGET_SHA }}
+          --github-run-id ${GITHUB_RUN_ID}
+          --test-duration-minutes ${{ env.TEST_DURATION_MINUTES }}
+      - name: Do we already have Performance Test graph results for this commit?
+        continue-on-error: true
+        id: check-already-have-performance-results
+        run: |
+          git checkout gh-pages;
+          HAS_RESULTS_ALREADY=$(
+            sed 's/window.BENCHMARK_DATA = //' soak-tests/per-commit-overall-results/data.js |
+            jq "
+              .entries |
+              .\"Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}\" |
+              any(.commit.id == \"${{ env.TARGET_SHA }}\")
+            " || echo false
+          );
+          git checkout main;
+          [[ $HAS_RESULTS_ALREADY == true ]]
+      - name: Graph and Report Performance Test Averages result
+        uses: benchmark-action/github-action-benchmark@v1
+        continue-on-error: true
+        id: check-failure-after-performance-tests
+        with:
+          name: Soak Test Results - sample-app-${{ matrix.app-platform }}-${{ matrix.instrumentation-type }}
+          tool: customSmallerIsBetter
+          output-file-path: output.json
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          max-items-in-chart: ${{ env.MAX_BENCHMARKS_TO_KEEP }}
+          alert-threshold: 175%
+          # Does not work as expected, see:
+          # https://github.com/open-telemetry/opentelemetry-python/pull/1478
+          # comment-always: true
+          fail-on-alert: true
+          auto-push: ${{ github.event_name == 'schedule' &&
+            steps.check-already-have-performance-results.outcome == 'failure' &&
+            github.ref == 'refs/heads/main' }}
+          gh-pages-branch: gh-pages
+          benchmark-data-dir-path: soak-tests/per-commit-overall-results
+      - name: Publish Issue if failed DURING Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: ${{ github.event_name == 'schedule' &&
+          steps.check-failure-during-performance-tests.outcome == 'failure' }}
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/auto-issue-templates/failure-during-soak_tests.md
+          update_existing: true
+      - name: Publish Issue if failed AFTER Performance Tests
+        uses: JasonEtco/create-an-issue@v2
+        if: ${{ github.event_name == 'schedule' &&
+          steps.check-failure-after-performance-tests.outcome == 'failure' }}
+        env:
+          APP_PLATFORM: ${{ matrix.app-platform }}
+          INSTRUMENTATION_TYPE: ${{ matrix.instrumentation-type }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          filename: .github/auto-issue-templates/failure-after-soak_tests.md
+          update_existing: true
+      - name: Check for Performance Degradation either DURING or AFTER Performance Tests
+        if: ${{ steps.check-failure-during-performance-tests.outcome == 'failure' ||
+          steps.check-failure-after-performance-tests.outcome == 'failure' }}
+        run: >-
+          echo 'Performance Tests failed, see the logs above for details';
+          exit 1;
